
/**
* Log_viewerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* mercoledì 28 gennaio 2009 10.20.07 CET
*/

public interface Log_viewerOperations 
{
  void setEnvironment (String[] Teams, String[] Drivers, short SegmentNumber, short T1, short T2, short RaceLaps);
  void updateLog (short Driver_ID, short Segment, short Speed);
  void endRace ();
} // interface Log_viewerOperations
