
/**
* Log_viewerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* martedì 27 gennaio 2009 10.33.29 CET
*/

public interface Log_viewerOperations 
{
  void updateLog (int Driver_ID, int Segment, int Speed);
  void endRace ();
} // interface Log_viewerOperations
