
/**
* Log_viewerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* martedì 27 gennaio 2009 10.33.29 CET
*/

abstract public class Log_viewerHelper
{
  private static String  _id = "IDL:Log_viewer:1.0";

  public static void insert (org.omg.CORBA.Any a, Log_viewer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Log_viewer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Log_viewerHelper.id (), "Log_viewer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Log_viewer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Log_viewerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Log_viewer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Log_viewer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Log_viewer)
      return (Log_viewer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _Log_viewerStub stub = new _Log_viewerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Log_viewer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Log_viewer)
      return (Log_viewer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _Log_viewerStub stub = new _Log_viewerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
