
/**
* StringsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* mercoledì 28 gennaio 2009 10.20.07 CET
*/

public final class StringsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringsHolder ()
  {
  }

  public StringsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringsHelper.type ();
  }

}
