typedef sequence<string> Strings;

interface Log_viewer {

  oneway void setEnvironment(
	in Strings Teams,
	in Strings Drivers,
	in short SegmentNumber,
	in short T1,
	in short T2,
	in short RaceLaps
  );

  oneway void updateLog (in short Driver_ID, in short Segment, in short Speed);

  oneway void endRace();

};
