package RI;


/**
* RI/Log_viewerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* sabato 20 giugno 2009 10.50.52 CEST
*/

public interface Log_viewerOperations 
{
  void setEnvironment (String[] Drivers, int segmentsNumber, short T1, short T2, short RaceLaps);
  void updateLog (short Driver_ID, int Segment, float Speed, boolean box);
  void endRace ();
} // interface Log_viewerOperations
