package RI;

/**
* RI/Log_viewerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* sabato 20 giugno 2009 10.50.52 CEST
*/

public final class Log_viewerHolder implements org.omg.CORBA.portable.Streamable
{
  public RI.Log_viewer value = null;

  public Log_viewerHolder ()
  {
  }

  public Log_viewerHolder (RI.Log_viewer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RI.Log_viewerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RI.Log_viewerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RI.Log_viewerHelper.type ();
  }

}
