
/**
* Log_viewer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* lunedì 11 maggio 2009 18.13.35 CEST
*/

public interface Log_viewer extends Log_viewerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Log_viewer
