
/**
* Log_viewer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* mercoledì 28 gennaio 2009 10.20.07 CET
*/

public interface Log_viewer extends Log_viewerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Log_viewer
