
/**
* Log_viewerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* martedì 27 gennaio 2009 10.33.28 CET
*/

public abstract class Log_viewerPOA extends org.omg.PortableServer.Servant
 implements Log_viewerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateLog", new java.lang.Integer (0));
    _methods.put ("endRace", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Log_viewer/updateLog
       {
         int Driver_ID = in.read_long ();
         int Segment = in.read_long ();
         int Speed = in.read_long ();
         this.updateLog (Driver_ID, Segment, Speed);
         out = $rh.createReply();
         break;
       }

       case 1:  // Log_viewer/endRace
       {
         this.endRace ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Log_viewer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Log_viewer _this() 
  {
    return Log_viewerHelper.narrow(
    super._this_object());
  }

  public Log_viewer _this(org.omg.CORBA.ORB orb) 
  {
    return Log_viewerHelper.narrow(
    super._this_object(orb));
  }


} // class Log_viewerPOA
