package RI;


/**
* RI/Log_viewer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from log_viewer.idl
* sabato 20 giugno 2009 10.50.52 CEST
*/

public interface Log_viewer extends Log_viewerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Log_viewer
