package RI;


/**
* RI/Log_viewer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/log/java/log_viewer.idl
* Wednesday, October 14, 2009 1:10:41 PM CEST
*/

public interface Log_viewer extends Log_viewerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Log_viewer
